### ISSUE TITLE
Linux building: The current Flutter SDK version is 0.0.0-unknown.

### ISSUE THREAD

**Issue by tsinis** [codemagic-ci-cd/flutter-desktop-docker#3] opened 2020-12-10 10:09 UTC
Sorry to bother you again. Yesterday the Linux builds worked again, but only on simple projects, without the third-party dependence from pub.dev. I tried to run my project, which contains quite a lot of dependencies, including those that are designed specifically for Linux, and unfortunately the building fails. I am attaching a log from building the master and dev branches. Something is wrong with the identification of the Flutter version on the Codemagic side, it says:
`The current Flutter SDK version is 0.0.0-unknown.`

[building_linux_dev.log](https://github.com/codemagic-ci-cd/flutter-desktop-docker/files/5671860/building_linux_dev.log)
[building_linux_master.log](https://github.com/codemagic-ci-cd/flutter-desktop-docker/files/5671861/building_linux_master.log)

The project is easily built on my local Ubuntu 20.04 LTS. The project repository is: https://github.com/tsinis/app_icon_tools

Thank you for your understanding.

**Comment by BondarenkoStas** [comment] 2020-12-13 09:38
@tsinis I believe the issue is fixed with https://github.com/codemagic-ci-cd/flutter-desktop-docker/pull/4. Thank you for your report!

**Closed as completed by BondarenkoStas** 2020-12-13 09:38 UTC

**Comment by tsinis** [comment] 2020-12-13 11:18
Can confirim its working again. Thanks.
